server:
  port: 7003

# Eureka注册中心配置 访问地址：http://${eureka.instance.hostname}:${server.port}/
eureka:
  instance:
    hostname: discover03        # Eureka服务端的实例名称
  client:
    register-with-eureka: false # 表示是否向eureka注册中心注册自己
    fetch-registry: false       # 如果为false，表示自己为注册中心
    service-url:                # 注册地址
      defaultZone: http://discovery02:7002/eureka/,http://discovery01:7001/eureka/  # 集群（关联）