server:
  port: 80


# Eureka配置
eureka:
  client:
    register-with-eureka: false # 不向Eureka注册自己
    fetch-registry: true
    service-url:
      defaultZone: http://discovery01:7001/eureka/,http://discovery02:7002/eureka/,http://discovery03:7003/eureka/


## 设置 feign 客户端超时时间（OpenFeign 默认支持 ribbon）（可以不加）
#ribbon:
#  # 值的是建立连接所用的时间，使用与网络状态正常的情况，两端连接所用的时间
#  ReadTimeout: 5000
#  # 指的是建立连接后从服务器读取到可用资源所用的时间
#  ConnectionTimeout: 5000